language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:

 ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'