language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

